stages:
  - test
  - deploy

Unit Testing:
  stage: test
  image: node:latest
  only:
    - main
  script:
    - npm install
    - npm run test

Publish to NPM:
  stage: deploy
  only:
    - main
  script:
    - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc
    - npm publish --access public